version: 0.2

phases:
  build:
    commands:
      - echo "Checking spelling ..." && ./pipeline.sh checkSpelling
      - echo "Checking links ..." && ./pipeline.sh checkLinks
      - echo "Creating release ..." && ./pipeline.sh createReleaseTag "v${CODEBUILD_RESOLVED_SOURCE_VERSION}" "${CODEBUILD_BUILD_NUMBER}"
      - echo "Publish pages"
