version: 0.2

phases:
  build:
    commands:
      - echo "Checking spelling ..." && ./pipeline.sh checkSpelling
      - echo "Checking links ..." && ./pipeline.sh checkLinks
      - env
      - echo "Creating release ..." && ./pipeline.sh createReleaseTag "${CODEBUILD_RESOLVED_SOURCE_VERSION}" "v${CODEBUILD_BUILD_NUMBER}"
      - echo "Publish pages"
