version: 0.2

phases:
  build:
    commands:
      - echo "Checking spelling ..." && ./pipeline.sh checkSpelling
      - echo "Checking links ..." && ./pipeline.sh checkLinks
      - echo "Create release"
      - echo "Publish pages"
